# config.yaml
user_agent: "MyOpenAlexTester/1.0"
referer: "https://example.com"
api_base: "https://api.openalex.org/works"
unpaywall_api: "https://api.unpaywall.org/v2"
email: null  # Set your real email here for Unpaywall API (required)
outdir: "pdfs"
email: "vardhanshorewala@berkeley.edu"